export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_OUT_GOOGLE = 'SIGN_OUT_GOOGLE';
export const SIGN_IN_FACEBOOK = 'SIGN_IN_FACEBOOK';
export const SIGN_OUT_FACEBOOK = 'SIGN_OUT_FACEBOOK';